### ISSUE TITLE
Error when calling fixtures.reset() without parameters

### ISSUE THREAD

**Issue by danielcosta27** [kennethklee/node-mongoose-fixtures#4]
Hi dear friend, how are you doing?

I just ran into an error when trying to reset my test database using fixtures.reset() without parameters.

The error message says: 
"TypeError: Cannot call method 'modelNames' of undefined"

I checked the source code and found the cause of this problem. How do you prefer to proceed? May I clone this project and send you a Pull request? Or only this message is enough?

Thanks a lot!

Daniel
![captura de tela 2015-02-23 02 02 09](https://cloud.githubusercontent.com/assets/9278768/6322999/08ddb82e-bb00-11e4-9986-4441ade4a68a.png)

**Comment by kennethklee** [comment]
Ah sorry about this. I didn't notice this issue in my mail. Feel free to fork and send a PR.

**Comment by kennethklee** [comment]
Too late. Fixed. =)
